### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alphapapa** [forrestchang/.doom.d#1]
https://github.com/forrestchang/.doom.d/blob/ab6406419aadcd393de7e0142f9fbcf57475ac3a/modules/private/my-org/config.el#L128

Hi,

FYI, that search should execute more quickly if the `todo` predicate appears first inside the `and` clause, like:

```el
'(and (todo "TODO" "STARTED" "BLOCKED")
      (or (scheduled :to today)
          (deadline :to today))
      (not (tags "PROJ"))
      (category "iqiyi" "pingduck" "workflow" "talk" "blog" "open-source" "programming"))
```
That's because the `todo` predicate's optimization can jump directly to items with those to-do keywords before comparing other predicates.  If the `(or (scheduled...)` clause is first, it tests every entry's scheduled or deadline timestamps, without skipping entries.  I hope to make the optimization smarter in the future, but for now, this has to be done manually by ordering the predicates.

**Comment by forrestchang** [comment]
@alphapapa Thanks, it's very helpful!
