### ISSUE TITLE
采用大神的配置，无法使用capture自定义模版

### ISSUE THREAD

**Issue by iT-Boyer** [forrestchang/.doom.d#2]
## 配置步骤
1. 在`+org.el`中使用`org-capture-templates`定义的org-capture模版
```el
(setq org-capture-templates nil)

;; Quick capture todo item to inbox
(add-to-list 'org-capture-templates
             '("t" "Todo" entry (file "~/hsg/hugo/org-notes/inbox.org")
               (file "~/.doom.d/templates/new-todo-template.org")))
```
2. 加载配置：config.el `(after! org (load! "+org"))`
3. doom刷新：`doom refresh`
4. 使用`SPC C`，但是**无法显示**：
![截屏2019-11-27下午12 32 19](https://user-images.githubusercontent.com/4022953/69693915-076eb200-1112-11ea-892c-48d29dfc6ebf.png)
如何能激活`+org.el`中的相关配置呢？
## 其他
尝试了以下有同样自定义需求，但在`+org.el`中都不生效：
```el
org-todo-keywords
org-tag-alist
org-agenda-custom-commands
```

**Comment by forrestchang** [comment]
使用 `SPC q R` 重启 Doom Emacs。
